### ISSUE TITLE
DSP8266 does not come out of deep sleep

### ISSUE THREAD

**Issue by carlosmaug** [mathew-hall/esp8266-dht#3]
Hi
When DSP8266 enters in deep sleep it never come out, I just get this string "��rl�l��|��쒒b�nnlnn�bp��rr��b�n" and it hangs for ever unless y disconnect and reconnect CH_PD (normally connected to 3.3V) or I make a reset.

Here is the output I get from the console.

��rl�l��|��쒒b�nnlnn�bp��rrp�n��lb|��ll`�nl`�n�p�n�r��n⌌��l`nll`�n`�n�l�nn�p�n�r��n⌎����l�n�nr���l`��l`rDHT Setupfor type 0, poll interval of 30000
Httpd init, conn=0x3ffea784
Temperature logging initialising
Got a DS18B20 Reading: 27.0
Ready
mode : sta(18:fe:34:9b:44:19)
add if0
scandone
add 0
aid 4
pm open phy2,type:2 0 0
cnt 

connected with ap1-casa, channel 11
dhcp client start...
ip:10.0.1.57,mask:255.255.255.0,gw:10.0.1.1
Logger: couldn't resolve IP address for bmo.local; will broadcast instead
Falling back on 7b00000a for logging
Successfully resolved bmo.local as 7b00000a
Will send to 10.0.0.123
Sending data
Sending heartbeat
DHT: 2b 00 1c 00 [47] CS: 47Temp =  2800 *C, Hum = 4300 % 
Got a DS18B20 Reading: 27.0Scheduling power down
Going to deep sleep mode now 
deep sleep 45s
��rl�l��|��쒒b�nnlnn�bp��rr��b�n

**Comment by carlosmaug** [comment]
Hi All
I found the answer in this web page http://www.esp8266.com/viewtopic.php?f=6&t=535
GPIO16 exists: it's XPD_DCDC you have to connect reset to this pin of the chip to come out of deep sleep.
It is not an easy task...
![img_20150510_175118](https://cloud.githubusercontent.com/assets/12379583/7555010/32464fa8-f73e-11e4-8dc0-dfdbd84729f6.jpg)

![esp8266_schema](https://cloud.githubusercontent.com/assets/12379583/7554988/d6167ace-f73c-11e4-80ea-1d598c9cfa16.png)

**Comment by mathew-hall** [comment]
Hi, thanks for raising this issue and attaching the circuit diagram and picture. I've linked them from the readme and hopefully made it a bit clearer.

Hope it all works now.
